// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmp4V0gqmSVizNWcuOVcI95eyxsKfl38',
    appId: '1:616159665054:web:1f071c8320fe9ff317148f',
    messagingSenderId: '616159665054',
    projectId: 'chat-app-95fbe',
    authDomain: 'chat-app-95fbe.firebaseapp.com',
    storageBucket: 'chat-app-95fbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVGmoxq9-vdJhMsOK7KozU6VdDeL0uXU',
    appId: '1:616159665054:android:2363390806c2379417148f',
    messagingSenderId: '616159665054',
    projectId: 'chat-app-95fbe',
    storageBucket: 'chat-app-95fbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzapayQ6afyAH2vysBpvW_Vn5TH5r17Q4',
    appId: '1:616159665054:ios:8c0fb9a065fdb51717148f',
    messagingSenderId: '616159665054',
    projectId: 'chat-app-95fbe',
    storageBucket: 'chat-app-95fbe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzapayQ6afyAH2vysBpvW_Vn5TH5r17Q4',
    appId: '1:616159665054:ios:8c0fb9a065fdb51717148f',
    messagingSenderId: '616159665054',
    projectId: 'chat-app-95fbe',
    storageBucket: 'chat-app-95fbe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
